server:
  port: ${PORT:8080}

spring:
  application:
      name: ${SPRING_APPLICATION_NAME:powerup-service}
      version: ${APP_VERSION:1.0.0}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/powerup}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
