server:
  port: ${PORT:8081}

spring:
  application:
      name: ${SPRING_APPLICATION_NAME:powerup-service}
      version: ${APP_VERSION:1.0.0}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/powerup}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:mi-secreto-super-seguro-para-jwt-en-todos-los-servicios-2024}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  tracing:
    sampling:
      probability: 1.0

# Microservices URLs (Feign/Integrations)
microservices:
  users:
    url: ${MICROSERVICES_USERS_URL:http://localhost:8081}
  orders:
    url: ${MICROSERVICES_ORDERS_URL:http://localhost:8082}
  messaging:
    url: ${MICROSERVICES_MESSAGING_URL:http://localhost:8083}
  restaurants:
    url: ${MICROSERVICES_RESTAURANTS_URL:http://localhost:8084}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
